name: 清理工作

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  clean-up:
    name: 清理工作
    runs-on: ubuntu-latest

    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.PA_TOKEN }}
          expire-in: 0
